### ISSUE TITLE
Hi, I want to know how can i get this file?  thank you

### ISSUE THREAD

**Issue by Wang946992** [LakeYang0818/Solving-Maxwells-Equation-by-PINN-Method#1]
![image](https://github.com/LakeYang0818/Solving-Maxwells-Equation-by-PINN-Method/assets/114710578/1392daaf-5546-45e4-9d19-f05b4ffb5b35)

**Comment by LakeYang0818** [comment]
Hi,
It’s the path of a folder.
Regards.


---- Replied Message ----

| From | ***@***.***> |
| Date | 07/19/2023 07:57 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [LakeYang0818/Solving-Maxwells-Equation-by-PINN-Method] Hi, I want to know how can i get this file? thank you (Issue #1) |
